In [1]:
import pandas as pd


In [2]:
X_test = pd.read_excel("Data_Train_Test\X_test.xlsx")
X_train = pd.read_excel("Data_Train_Test\X_train.xlsx")
y_test_true = pd.read_excel("Data_Train_Test\y_test_true.xlsx")
y_train_true = pd.read_excel("Data_Train_Test\y_train_true.xlsx")


In [3]:
# Read Transform
X_test_trans = pd.read_excel("Data_Trans\X_test_trans.xlsx")
X_train_trans = pd.read_excel("Data_Trans\X_train_trans.xlsx")


In [4]:
# Start Training
# Linear Regression

from sklearn.linear_model import LinearRegression

LinearRegressionOBJ = LinearRegression()

LinearRegressionOBJ.fit(X_train_trans,y_train_true)




LinearRegression()

In [5]:
# Save Linear Model
import joblib 
joblib.dump(LinearRegressionOBJ,"Model_Files/LinearModel.pkl")


['Model_Files/LinearModel.pkl']

In [6]:
LinearModel_1 = joblib.load("Model_Files\LinearModel.pkl")


In [7]:
# PREDICT y_train_pred
# PREDICT y_test_pred
y_train_pred = LinearModel_1.predict(X_train_trans)
y_train_pred



array([[116377.30474493],
       [113831.11284144],
       [ 76042.01151239],
       [ 60219.21128593],
       [178797.05217119],
       [118591.50886292],
       [ 49339.69240356],
       [135265.23023493],
       [ 96229.00021739],
       [164175.97033019],
       [122106.50496056],
       [  1404.05641278],
       [136072.10844169],
       [124662.44592762],
       [ 76521.29554029],
       [171353.30754293],
       [171696.87555894],
       [136005.97338565],
       [271719.01287978],
       [125099.70772509],
       [118377.70413544],
       [132432.68210148],
       [ 67896.9104651 ],
       [ 89360.68198072],
       [ 68492.01239291],
       [137158.95888814],
       [ 95959.44064322],
       [142124.8500433 ],
       [ 87319.2355628 ],
       [ 48241.86532538],
       [221895.16403314],
       [ 73531.73211214],
       [172338.6420808 ],
       [171895.68252207],
       [141859.20940142],
       [117746.65834524],
       [131977.34864672],
       [136041.57611141],
       [ 974

In [8]:
y_test_pred = LinearModel_1.predict(X_test_trans)


In [9]:
from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score
import numpy as np

def linear_Metrics(x_Data,True_Value,Pred_Value):

    MSE = mean_squared_error(True_Value,Pred_Value) 
    MAE = mean_absolute_error(True_Value,Pred_Value)
    RMSE = np.sqrt(MSE)
    R2 = r2_score(True_Value,Pred_Value)

    n = len(x_Data)
    p = x_Data.shape[1]
    A_R2 = 1-(1-R2)*(n-1)/(n-p-1)

    merticsDict = {"MSE": MSE,
                   "MAE":MAE,
                   "RMSE": RMSE,
                   "R2": R2,
                   "A_R2":A_R2}
    return merticsDict




In [10]:
# Training Evaluation
linear_Metrics(X_train,y_train_true,y_train_pred)


{'MSE': 1183774272.5226266,
 'MAE': 22121.21604254765,
 'RMSE': 34406.02087604184,
 'R2': 0.7709186592540871,
 'A_R2': 0.7554749733611043}

In [11]:
# Testing Evaluation
linear_Metrics(X_test,y_test_true,y_test_pred)


{'MSE': 5711948667.789252,
 'MAE': 41762.12472052147,
 'RMSE': 75577.43491141553,
 'R2': 0.663897273496076,
 'A_R2': 0.5452727817888087}

In [15]:
# Train using Lasso

from sklearn.linear_model import Lasso

LassoModel = Lasso(alpha=0.1)
LassoModel.fit(X_train_trans,y_train_true)


Lasso(alpha=0.1)

In [16]:
# import joblib file
import joblib

joblib.dump(LassoModel,"Model_Files/Lasso_Model.pkl")


['Model_Files/Lasso_Model.pkl']

In [ ]:
# Load the Lasso Model
Lasso_Model_1 = joblib.load("Model_Files/Lasso_Model.pkl")
Lasso_Model_1

Lasso_Model_1


Lasso(alpha=0.1)

In [19]:
# y_train_pred
y_train_pred = Lasso_Model_1.predict(X_train_trans)
y_train_pred



array([116378.2325393 , 113832.51470668,  76042.88511015,  60220.44222106,
       178796.88699399, 118590.85869002,  49340.62186931, 135265.71323803,
        96229.97371769, 164175.86876512, 122107.35813694,   1405.13341115,
       136072.25471762, 124663.84874792,  76522.681416  , 171354.26341871,
       171698.70652108, 136006.67398703, 271719.29487448, 125100.60312277,
       118376.77695413, 132432.21680995,  67893.58429845,  89361.1821685 ,
        68493.07090279, 137159.34862562,  95956.76770935, 142125.89065647,
        87320.07502421,  48242.51026571, 221894.9790994 ,  73532.74895707,
       172339.63510338, 171896.28337999, 141859.17160568, 117742.9573089 ,
       131977.25397561, 136037.11491259,  97486.84996264, 142606.16728855,
       158318.04640592, 113253.9725244 ,  75651.44819315, 103809.11764628,
       131585.7168186 , 106932.86801174, 169384.81358536,   4868.14415377,
        72669.86323841,  95392.07177369,   3188.18984024, 119998.34047716,
       124712.75620182, 2

In [20]:
# y_test_pred
y_test_pred = Lasso_Model_1.predict(X_test_trans)
y_test_pred



array([ 70916.95105635, 123258.38513582,  62315.81286324, 178311.48082358,
        49766.87659127,  72768.30996648, 175220.89875303,  53218.16676704,
        65025.75205901, 381900.05884505,  99720.42462466, 164273.66032613,
       150051.23722238,  96313.43330036,  91704.4958998 , 137817.91381257,
       178510.02019447, 108891.8554622 , 182672.73026586, 300030.40243965,
       115936.36888108,  89464.70321421,  71972.29706456, 143834.35012968])

In [22]:
# Trainig DATA Evaluation
linear_Metrics(X_train,y_train_true,y_train_pred)


{'MSE': 1183774274.863149,
 'MAE': 22121.138782659767,
 'RMSE': 34406.0209100551,
 'R2': 0.7709186588011544,
 'A_R2': 0.7554749728776368}

In [25]:
# Test Evaluation

linear_Metrics(X_test,y_test_true,y_test_pred)


{'MSE': 5711987807.773913,
 'MAE': 41762.1888524938,
 'RMSE': 75577.69385059267,
 'R2': 0.6638949704194336,
 'A_R2': 0.5452696658615865}