# Read the DATA

In [18]:
import pandas as pd


In [19]:
X_test = pd.read_excel("Data_Train_Test\X_test.xlsx")
X_train = pd.read_excel("Data_Train_Test\X_train.xlsx")
y_test_true = pd.read_excel("Data_Train_Test\y_test_true.xlsx")
y_train_true = pd.read_excel("Data_Train_Test\y_train_true.xlsx")


In [20]:
# Read Transform
X_test_trans = pd.read_excel("Data_Trans\X_test_trans.xlsx")
X_train_trans = pd.read_excel("Data_Trans\X_train_trans.xlsx")


# Linear Regression Training

In [21]:
# Start Training
# Linear Regression

from sklearn.linear_model import LinearRegression

LinearRegressionOBJ = LinearRegression()

LinearRegressionOBJ.fit(X_train_trans,y_train_true)




,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](1, 11)","[[ 116.59,22896.43, 3049.62,...,25948.98,32809.45, 6481.84]]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](11,)","['Unnamed: 0','Oridnal_Encoder__Designation','Oridnal_Encoder__Education', ...,'Numerical_Coluns__TenureYears','Numerical_Coluns__ProjectsCompleted', 'Numerical_Coluns__PerformanceScore']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.","ndarray[float64](1,)",[91869.21]
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,11
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(11)


In [22]:
# Save Linear Model
import joblib 
joblib.dump(LinearRegressionOBJ,"Model_Files/LinearModel.pkl")


['Model_Files/LinearModel.pkl']

In [23]:
LinearModel_1 = joblib.load("Model_Files\LinearModel.pkl")


In [24]:
# PREDICT y_train_pred
# PREDICT y_test_pred
y_train_pred = LinearModel_1.predict(X_train_trans)
y_train_pred



array([[116377.30474493],
       [113831.11284144],
       [ 76042.01151239],
       [ 60219.21128593],
       [178797.05217119],
       [118591.50886292],
       [ 49339.69240356],
       [135265.23023493],
       [ 96229.00021739],
       [164175.97033019],
       [122106.50496056],
       [  1404.05641278],
       [136072.10844169],
       [124662.44592762],
       [ 76521.29554029],
       [171353.30754293],
       [171696.87555894],
       [136005.97338565],
       [271719.01287978],
       [125099.70772509],
       [118377.70413544],
       [132432.68210148],
       [ 67896.9104651 ],
       [ 89360.68198072],
       [ 68492.01239291],
       [137158.95888814],
       [ 95959.44064322],
       [142124.8500433 ],
       [ 87319.2355628 ],
       [ 48241.86532538],
       [221895.16403314],
       [ 73531.73211214],
       [172338.6420808 ],
       [171895.68252207],
       [141859.20940142],
       [117746.65834524],
       [131977.34864672],
       [136041.57611141],
       [ 974

In [25]:
y_test_pred = LinearModel_1.predict(X_test_trans)


# Linear metrics Function

In [26]:
from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score
import numpy as np

def linear_Metrics(x_Data,True_Value,Pred_Value):

    MSE = mean_squared_error(True_Value,Pred_Value) 
    MAE = mean_absolute_error(True_Value,Pred_Value)
    RMSE = np.sqrt(MSE)
    R2 = r2_score(True_Value,Pred_Value)

    n = len(x_Data)
    p = x_Data.shape[1]
    A_R2 = 1-(1-R2)*(n-1)/(n-p-1)

    merticsDict = {"MSE": MSE,
                   "MAE":MAE,
                   "RMSE": RMSE,
                   "R2": R2,
                   "A_R2":A_R2}
    return merticsDict




In [27]:
# Training Evaluation
linear_Metrics(X_train,y_train_true,y_train_pred)


{'MSE': 1183774272.5226262,
 'MAE': 22121.21604254766,
 'RMSE': np.float64(34406.02087604183),
 'R2': 0.7709186592540871,
 'A_R2': 0.7554749733611043}

In [28]:
# Testing Evaluation
linear_Metrics(X_test,y_test_true,y_test_pred)


{'MSE': 5711948667.789251,
 'MAE': 41762.12472052147,
 'RMSE': np.float64(75577.43491141553),
 'R2': 0.6638972734960762,
 'A_R2': 0.545272781788809}

# Lasso Model Training

In [29]:
# Train using Lasso

from sklearn.linear_model import Lasso

LassoModel = Lasso(alpha=0.1)
LassoModel.fit(X_train_trans,y_train_true)


,"alpha alpha: float, default=1.0Constant that multiplies the L1 term, controlling regularizationstrength. `alpha` must be a non-negative float i.e. in `[0, inf)`.When `alpha = 0`, the objective is equivalent to ordinary leastsquares, solved by the :class:`LinearRegression` object. For numericalreasons, using `alpha = 0` with the `Lasso` object is not advised.Instead, you should use the :class:`LinearRegression` object.",0.1
,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"precompute precompute: bool or array-like of shape (n_features, n_features), default=FalseWhether to use a precomputed Gram matrix to speed upcalculations. The Gram matrix can also be passed as argument.For sparse input this option is always ``False`` to preserve sparsity.",False
,"copy_X copy_X: bool, default=TrueIf ``True``, X will be copied; else, it may be overwritten.",True
,"max_iter max_iter: int, default=1000The maximum number of iterations.",1000
,"tol tol: float, default=1e-4The tolerance for the optimization: if the updates are smaller or equal to``tol``, the optimization code checks the dual gap for optimality and continuesuntil it is smaller or equal to ``tol``, see Notes below.",0.0001
,"warm_start warm_start: bool, default=FalseWhen set to ``True``, reuse the solution of the previous call to fit asinitialization, otherwise, just erase the previous solution.See :term:`the Glossary <warm_start>`.",False
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive.",False
,"random_state random_state: int, RandomState instance, default=NoneThe seed of the pseudo random number generator that selects a randomfeature to update. Used when ``selection`` == 'random'.Pass an int for reproducible output across multiple function calls.See :term:`Glossary <random_state>`.",None
,"selection selection: {'cyclic', 'random'}, default='cyclic'If set to 'random', a random coefficient is updated every iterationrather than looping over features sequentially by default. This(setting to 'random') often leads to significantly faster convergenceespecially when tol is higher than 1e-4.",'cyclic'
Name,Type,Value


In [30]:
# import joblib file
import joblib

joblib.dump(LassoModel,"Model_Files/Lasso_Model.pkl")


['Model_Files/Lasso_Model.pkl']

In [31]:
# Load the Lasso Model
Lasso_Model_1 = joblib.load("Model_Files/Lasso_Model.pkl")
Lasso_Model_1

Lasso_Model_1


,"alpha alpha: float, default=1.0Constant that multiplies the L1 term, controlling regularizationstrength. `alpha` must be a non-negative float i.e. in `[0, inf)`.When `alpha = 0`, the objective is equivalent to ordinary leastsquares, solved by the :class:`LinearRegression` object. For numericalreasons, using `alpha = 0` with the `Lasso` object is not advised.Instead, you should use the :class:`LinearRegression` object.",0.1
,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"precompute precompute: bool or array-like of shape (n_features, n_features), default=FalseWhether to use a precomputed Gram matrix to speed upcalculations. The Gram matrix can also be passed as argument.For sparse input this option is always ``False`` to preserve sparsity.",False
,"copy_X copy_X: bool, default=TrueIf ``True``, X will be copied; else, it may be overwritten.",True
,"max_iter max_iter: int, default=1000The maximum number of iterations.",1000
,"tol tol: float, default=1e-4The tolerance for the optimization: if the updates are smaller or equal to``tol``, the optimization code checks the dual gap for optimality and continuesuntil it is smaller or equal to ``tol``, see Notes below.",0.0001
,"warm_start warm_start: bool, default=FalseWhen set to ``True``, reuse the solution of the previous call to fit asinitialization, otherwise, just erase the previous solution.See :term:`the Glossary <warm_start>`.",False
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive.",False
,"random_state random_state: int, RandomState instance, default=NoneThe seed of the pseudo random number generator that selects a randomfeature to update. Used when ``selection`` == 'random'.Pass an int for reproducible output across multiple function calls.See :term:`Glossary <random_state>`.",None
,"selection selection: {'cyclic', 'random'}, default='cyclic'If set to 'random', a random coefficient is updated every iterationrather than looping over features sequentially by default. This(setting to 'random') often leads to significantly faster convergenceespecially when tol is higher than 1e-4.",'cyclic'
Name,Type,Value


In [32]:
# y_train_pred
y_train_pred = Lasso_Model_1.predict(X_train_trans)
y_train_pred



array([116378.2325393 , 113832.51470668,  76042.88511015,  60220.44222106,
       178796.88699399, 118590.85869002,  49340.62186931, 135265.71323803,
        96229.97371769, 164175.86876512, 122107.35813694,   1405.13341115,
       136072.25471762, 124663.84874792,  76522.681416  , 171354.26341871,
       171698.70652108, 136006.67398703, 271719.29487448, 125100.60312277,
       118376.77695413, 132432.21680995,  67893.58429845,  89361.1821685 ,
        68493.07090279, 137159.34862562,  95956.76770935, 142125.89065647,
        87320.07502421,  48242.51026571, 221894.9790994 ,  73532.74895707,
       172339.63510338, 171896.28337999, 141859.17160568, 117742.9573089 ,
       131977.25397561, 136037.11491259,  97486.84996264, 142606.16728855,
       158318.04640592, 113253.9725244 ,  75651.44819315, 103809.11764628,
       131585.7168186 , 106932.86801174, 169384.81358536,   4868.14415377,
        72669.86323841,  95392.07177369,   3188.18984024, 119998.34047716,
       124712.75620182, 2

In [33]:
# y_test_pred
y_test_pred = Lasso_Model_1.predict(X_test_trans)
y_test_pred



array([ 70916.95105635, 123258.38513582,  62315.81286324, 178311.48082358,
        49766.87659127,  72768.30996648, 175220.89875303,  53218.16676704,
        65025.75205901, 381900.05884505,  99720.42462466, 164273.66032613,
       150051.23722238,  96313.43330036,  91704.4958998 , 137817.91381257,
       178510.02019447, 108891.8554622 , 182672.73026586, 300030.40243965,
       115936.36888108,  89464.70321421,  71972.29706456, 143834.35012968])

In [34]:
# Trainig DATA Evaluation
linear_Metrics(X_train,y_train_true,y_train_pred)


{'MSE': 1183774274.863149,
 'MAE': 22121.13878265978,
 'RMSE': np.float64(34406.0209100551),
 'R2': 0.7709186588011544,
 'A_R2': 0.7554749728776368}

In [35]:
# Test Evaluation

linear_Metrics(X_test,y_test_true,y_test_pred)


{'MSE': 5711987807.773911,
 'MAE': 41762.18885249379,
 'RMSE': np.float64(75577.69385059267),
 'R2': 0.6638949704194337,
 'A_R2': 0.5452696658615868}

# DTR training

In [36]:
from sklearn.tree import DecisionTreeRegressor

DTR_Obj = DecisionTreeRegressor()
DTR_Obj.fit(X_train_trans,y_train_true)


,"criterion criterion: {""squared_error"", ""absolute_error"", ""poisson""}, default=""squared_error""The function to measure the quality of a split. Supported criteriaare ""squared_error"" for the mean squared error, which is equal tovariance reduction as feature selection criterion and minimizes the L2loss using the mean of each terminal node, ""absolute_error"" for the meanabsolute error, which minimizes the L1 loss using the median of each terminalnode, and ""poisson"" which uses reduction in Poisson deviance to find splits,also using the mean of each terminal node... versionadded:: 0.18 Mean Absolute Error (MAE) criterion... versionadded:: 0.24 Poisson deviance criterion... versionchanged:: 1.9 Criterion `""friedman_mse""` was deprecated.",'squared_error'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.For an example of how ``max_depth`` influences the model, see:ref:`sphx_glr_auto_examples_tree_plot_tree_regression.py`.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary <random_state>` for details.",None
,"max_leaf_node

In [37]:
# Save the Model in Model_Files
import joblib
joblib.dump(DTR_Obj,"Model_Files/DTR_Obj.pkl")


['Model_Files/DTR_Obj.pkl']

In [38]:
# Genereate y_train_pred and y_test_pred

DTR_Obj_01 = joblib.load("Model_Files/DTR_Obj.pkl")


In [39]:
# Genereate y_train_pred 
y_train_pred = DTR_Obj_01.predict(X_train_trans)
y_train_pred


array([ 78100., 146000.,  98500.,  60000., 167400., 126200.,  94700.,
       129600., 110600., 146800.,  93300.,  28000., 142400., 155300.,
        65000., 152800., 157800., 131000., 235200., 122800., 117800.,
       111100.,  93100.,  76700.,  81300., 115300.,  81700., 134100.,
       106300.,  70700., 218200.,  55000., 162400., 168900.,  97900.,
       136800., 109400., 139200., 107000., 118200., 310000., 118500.,
       100400., 101200., 137200., 115100., 134700.,  25000.,  65600.,
        77000.,  32500., 131100., 126300., 239300., 169900., 109800.,
       104700.,  96600.,  80000.,  92700., 133300.,  99400.,  93100.,
       138200., 480000.,  98000., 151300.,  87800.,  40000., 119200.,
        98300., 395000.,  71400.,  95100.,  90000., 212200., 171800.,
       113800., 139400., 111000., 290000.,  89600., 145500., 380000.,
       142800., 159100., 121700.,  58000., 151000., 119900.,  72100.,
        40000.,  76900., 168900., 149700.,  55000.])

In [40]:
# Genereate y_test_pred
y_test_pred = DTR_Obj_01.predict(X_test_trans)
y_test_pred


array([119200., 133300.,  65600., 168900.,  71400., 119200., 131000.,
        65600.,  78100., 395000., 101200., 149700., 218200.,  98300.,
       110600.,  65000.,  60000., 110600., 168900., 395000., 133300.,
       134700.,  81700., 149700.])

In [41]:
#  Evaluatoin Training Data
linear_Metrics(X_train,y_train_true,y_train_pred)


{'MSE': 0.0, 'MAE': 0.0, 'RMSE': np.float64(0.0), 'R2': 1.0, 'A_R2': 1.0}

In [42]:
# Evaluation on Testing Data
linear_Metrics(X_test,y_test_true,y_test_pred)


{'MSE': 6532262500.0,
 'MAE': 41566.666666666664,
 'RMSE': np.float64(80822.41335174297),
 'R2': 0.6156283320838933,
 'A_R2': 0.4799677434076204}