# Read the DATA

In [40]:
import pandas as pd


In [41]:
# pip install openpyxl


In [42]:
X_test = pd.read_excel("Data_Train_Test/X_test.xlsx")
X_train = pd.read_excel("Data_Train_Test/X_train.xlsx")
y_test_true = pd.read_excel("Data_Train_Test/y_test_true.xlsx")
y_train_true = pd.read_excel("Data_Train_Test/y_train_true.xlsx")


In [43]:
# Read Transform
X_test_trans = pd.read_excel("Data_Trans\X_test_trans.xlsx")
X_train_trans = pd.read_excel("Data_Trans\X_train_trans.xlsx")


# Linear Regression Training

In [44]:
# Start Training
# Linear Regression

from sklearn.linear_model import LinearRegression

LinearRegressionOBJ = LinearRegression()

LinearRegressionOBJ.fit(X_train_trans,y_train_true)




LinearRegression()

In [45]:
# Save Linear Model
import joblib 
joblib.dump(LinearRegressionOBJ,"Model_Files/LinearModel.pkl")


['Model_Files/LinearModel.pkl']

In [46]:
LinearModel_1 = joblib.load("Model_Files\LinearModel.pkl")


In [47]:
# PREDICT y_train_pred
# PREDICT y_test_pred
y_train_pred = LinearModel_1.predict(X_train_trans)
y_train_pred



array([[116377.30474493],
       [113831.11284144],
       [ 76042.01151239],
       [ 60219.21128593],
       [178797.05217119],
       [118591.50886292],
       [ 49339.69240356],
       [135265.23023493],
       [ 96229.00021739],
       [164175.97033019],
       [122106.50496056],
       [  1404.05641278],
       [136072.10844169],
       [124662.44592762],
       [ 76521.29554029],
       [171353.30754293],
       [171696.87555894],
       [136005.97338565],
       [271719.01287978],
       [125099.70772509],
       [118377.70413544],
       [132432.68210148],
       [ 67896.9104651 ],
       [ 89360.68198072],
       [ 68492.01239291],
       [137158.95888814],
       [ 95959.44064322],
       [142124.8500433 ],
       [ 87319.2355628 ],
       [ 48241.86532538],
       [221895.16403314],
       [ 73531.73211214],
       [172338.6420808 ],
       [171895.68252207],
       [141859.20940142],
       [117746.65834524],
       [131977.34864672],
       [136041.57611141],
       [ 974

In [48]:
y_test_pred = LinearModel_1.predict(X_test_trans)


# Linear metrics Function

In [49]:
from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score
import numpy as np

def linear_Metrics(x_Data,True_Value,Pred_Value):

    MSE = mean_squared_error(True_Value,Pred_Value) 
    MAE = mean_absolute_error(True_Value,Pred_Value)
    RMSE = np.sqrt(MSE)
    R2 = r2_score(True_Value,Pred_Value)

    n = len(x_Data)
    p = x_Data.shape[1]
    A_R2 = 1-(1-R2)*(n-1)/(n-p-1)

    merticsDict = {"MSE": MSE,
                   "MAE":MAE,
                   "RMSE": RMSE,
                   "R2": R2,
                   "A_R2":A_R2}
    return merticsDict




In [50]:
# Training Evaluation
linear_Metrics(X_train,y_train_true,y_train_pred)


{'MSE': 1183774272.5226266,
 'MAE': 22121.21604254766,
 'RMSE': 34406.02087604184,
 'R2': 0.7709186592540871,
 'A_R2': 0.7554749733611043}

In [51]:
# Testing Evaluation
linear_Metrics(X_test,y_test_true,y_test_pred)


{'MSE': 5711948667.78926,
 'MAE': 41762.12472052145,
 'RMSE': 75577.43491141559,
 'R2': 0.6638972734960756,
 'A_R2': 0.5452727817888081}

# Lasso Model Training

In [52]:
# Train using Lasso

from sklearn.linear_model import Lasso

LassoModel = Lasso(alpha=0.1)
LassoModel.fit(X_train_trans,y_train_true)


Lasso(alpha=0.1)

In [53]:
# import joblib file
import joblib

joblib.dump(LassoModel,"Model_Files/Lasso_Model.pkl")


['Model_Files/Lasso_Model.pkl']

In [54]:
# Load the Lasso Model
Lasso_Model_1 = joblib.load("Model_Files/Lasso_Model.pkl")
Lasso_Model_1

Lasso_Model_1


Lasso(alpha=0.1)

In [55]:
# y_train_pred
y_train_pred = Lasso_Model_1.predict(X_train_trans)
y_train_pred



array([116378.2325393 , 113832.51470668,  76042.88511015,  60220.44222106,
       178796.88699399, 118590.85869002,  49340.62186931, 135265.71323803,
        96229.97371769, 164175.86876512, 122107.35813694,   1405.13341115,
       136072.25471762, 124663.84874792,  76522.681416  , 171354.26341871,
       171698.70652108, 136006.67398703, 271719.29487448, 125100.60312277,
       118376.77695413, 132432.21680995,  67893.58429845,  89361.1821685 ,
        68493.07090279, 137159.34862562,  95956.76770935, 142125.89065647,
        87320.07502421,  48242.51026571, 221894.9790994 ,  73532.74895707,
       172339.63510338, 171896.28337999, 141859.17160568, 117742.9573089 ,
       131977.25397561, 136037.11491259,  97486.84996264, 142606.16728855,
       158318.04640592, 113253.9725244 ,  75651.44819315, 103809.11764628,
       131585.7168186 , 106932.86801174, 169384.81358536,   4868.14415377,
        72669.86323841,  95392.07177369,   3188.18984024, 119998.34047716,
       124712.75620182, 2

In [56]:
# y_test_pred
y_test_pred = Lasso_Model_1.predict(X_test_trans)
y_test_pred



array([ 70916.95105635, 123258.38513582,  62315.81286324, 178311.48082358,
        49766.87659127,  72768.30996648, 175220.89875303,  53218.16676704,
        65025.75205901, 381900.05884505,  99720.42462466, 164273.66032613,
       150051.23722238,  96313.43330036,  91704.4958998 , 137817.91381257,
       178510.02019447, 108891.8554622 , 182672.73026586, 300030.40243965,
       115936.36888108,  89464.70321421,  71972.29706456, 143834.35012968])

In [57]:
# Trainig DATA Evaluation
linear_Metrics(X_train,y_train_true,y_train_pred)


{'MSE': 1183774274.8631487,
 'MAE': 22121.138782659782,
 'RMSE': 34406.0209100551,
 'R2': 0.7709186588011545,
 'A_R2': 0.7554749728776369}

In [58]:
# Test Evaluation

linear_Metrics(X_test,y_test_true,y_test_pred)


{'MSE': 5711987807.773909,
 'MAE': 41762.188852493775,
 'RMSE': 75577.69385059264,
 'R2': 0.6638949704194339,
 'A_R2': 0.545269665861587}

# DTR training

In [59]:
from sklearn.tree import DecisionTreeRegressor

DTR_Obj = DecisionTreeRegressor()
DTR_Obj.fit(X_train_trans,y_train_true)


DecisionTreeRegressor()

In [60]:
# Save the Model in Model_Files
import joblib
joblib.dump(DTR_Obj,"Model_Files/DTR_Obj.pkl")


['Model_Files/DTR_Obj.pkl']

In [61]:
# Genereate y_train_pred and y_test_pred
DTR_Obj_01 = joblib.load("Model_Files/DTR_Obj.pkl")


In [62]:
# Genereate y_train_pred 
y_train_pred = DTR_Obj_01.predict(X_train_trans)
y_train_pred


array([ 78100., 146000.,  98500.,  60000., 167400., 126200.,  94700.,
       129600., 110600., 146800.,  93300.,  28000., 142400., 155300.,
        65000., 152800., 157800., 131000., 235200., 122800., 117800.,
       111100.,  93100.,  76700.,  81300., 115300.,  81700., 134100.,
       106300.,  70700., 218200.,  55000., 162400., 168900.,  97900.,
       136800., 109400., 139200., 107000., 118200., 310000., 118500.,
       100400., 101200., 137200., 115100., 134700.,  25000.,  65600.,
        77000.,  32500., 131100., 126300., 239300., 169900., 109800.,
       104700.,  96600.,  80000.,  92700., 133300.,  99400.,  93100.,
       138200., 480000.,  98000., 151300.,  87800.,  40000., 119200.,
        98300., 395000.,  71400.,  95100.,  90000., 212200., 171800.,
       113800., 139400., 111000., 290000.,  89600., 145500., 380000.,
       142800., 159100., 121700.,  58000., 151000., 119900.,  72100.,
        40000.,  76900., 168900., 149700.,  55000.])

In [63]:
# Genereate y_test_pred
y_test_pred = DTR_Obj_01.predict(X_test_trans)
y_test_pred


array([119200., 137200.,  72100., 169900.,  71400., 119200., 131000.,
        71400.,  65600., 395000., 101200., 149700., 212200.,  98300.,
       110600.,  65000.,  58000., 111100., 169900., 380000., 137200.,
       137200.,  95100., 131100.])

In [64]:
#  Evaluatoin Training Data
linear_Metrics(X_train,y_train_true,y_train_pred)


{'MSE': 0.0, 'MAE': 0.0, 'RMSE': 0.0, 'R2': 1.0, 'A_R2': 1.0}

In [65]:
# Evaluation on Testing Data
linear_Metrics(X_test,y_test_true,y_test_pred)


{'MSE': 6779107500.0,
 'MAE': 42766.666666666664,
 'RMSE': 82335.33567065845,
 'R2': 0.6011034680927798,
 'A_R2': 0.460316456831408}

#  Random Forest Regressor

In [66]:
from sklearn.ensemble import RandomForestRegressor
import joblib
RFR = RandomForestRegressor()
RFR.fit(X_train_trans,y_train_true)

joblib.dump(RFR,"Model_Files/RFR.pkl")


C:\Users\SHIVRAJ SHINDE\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


['Model_Files/RFR.pkl']

In [67]:
# Generate Predected Values Train and Test

RFR_01 = joblib.load("Model_Files\RFR.pkl")
RFR_01


RandomForestRegressor()

In [68]:
# Traing Pred 
y_train_pred = RFR_01.predict(X_train_trans)
y_train_pred


array([ 82519., 138510., 102712.,  58627., 162658., 122075.,  95475.,
       126147., 113578., 144358.,  93753.,  31040., 136891., 154635.,
        67675., 160709., 156721., 136349., 229012., 124579., 111318.,
       113975.,  91970.,  84285.,  82750., 117299.,  81056., 136692.,
       107141.,  72677., 214552.,  64968., 150457., 159480.,  96378.,
       138576., 107343., 134988., 107047., 117125., 236220., 121799.,
        98716., 107028., 131396., 120582., 134673.,  30847.,  71795.,
        78854.,  35708., 136713., 127032., 225054., 167221., 105845.,
       107297.,  99313.,  81901.,  93072., 131211., 103083.,  91817.,
       140517., 435816.,  96912., 147099.,  91090.,  44372., 113411.,
       101394., 322256.,  74761.,  89823., 118016., 210972., 169245.,
       108166., 143424., 108044., 227240.,  91205., 144443., 380528.,
       148222., 162645., 121331.,  58970., 146293., 117228.,  74282.,
       116965.,  76206., 169704., 155742., 147706.])

In [70]:
# Traing Pred 
y_test_pred = RFR_01.predict(X_test_trans)
y_test_pred


array([105175., 130585.,  94939., 155590.,  81183., 102902., 152311.,
        73043.,  86496., 391752., 108666., 145590., 205415., 101050.,
       116737., 131900.,  98459., 111391., 154532., 331443., 129889.,
       128132.,  86713., 147783.])

In [71]:
# Evaluation Training 
linear_Metrics(X_train,y_train_true,y_train_pred)


{'MSE': 349841047.65625,
 'MAE': 7874.239583333333,
 'RMSE': 18704.03827135333,
 'R2': 0.932299545525461,
 'A_R2': 0.9277354699429078}

In [72]:
# Evaluation Testing
linear_Metrics(X_test,y_test_true,y_test_pred)


{'MSE': 6089611185.083333,
 'MAE': 36397.0,
 'RMSE': 78035.96084551874,
 'R2': 0.6416748395871936,
 'A_R2': 0.5152071359120856}

In [ ]:
# prerform traiing on AdaBoostRegressor
from sklearn.ensemble import AdaBoostRegressor


In [ ]:
# perform training on  GradientBoostingRegressor
from sklearn.ensemble import GradientBoostingRegressor
